variable "namespace" {}
variable "resource_tag_name" {}
variable "ami" {}
variable "instance_type" {}
variable "user_data" {}
variable "subnet_id" {}
variable "associate_public_ip_address" {}
variable "iam_instance_profile" {}
variable "key_name" {}
variable "rds_port" {}